### ISSUE TITLE
isBoxSizeOuter always false in Chrome with Windows custom dpi scaling

### ISSUE THREAD

**Issue by kscdre** [desandro/get-size#12]
This only occurs on Windows when a **custom** scale for the display is set in the operating system. For example 140%, instead of the default 100,125,150, etc.. recommended choices Windows gives you.

When using a custom scale, style.width will not be set to a round 200 pixels, but instead is something like 199.993px, causing this line to always be false when it should be true:

getSize.isBoxSizeOuter = isBoxSizeOuter = getStyleSize( style.width ) == 200;

I fixed it in my project with a simple Math.round(), I'd imagine that's probably a safe fix for all scenarios.

**Comment by desandro** [comment]
Sounds good! If you submit a Pull Request with this addition, I'll add it

**Comment by desandro** [comment]
`v2.0.3` has been released with this fix added. Thanks again for reporting the issue!
