### ISSUE TITLE
elem.offsetWidth is wrong on custom elements with shadow dom

### ISSUE THREAD

**Issue by mburger81** [desandro/get-size#13]
We use your masonry lib and have some problems with styling it right after first init.

When we init masonry and there are no elements, which came async from angular service the web components are added in a second moment when data came from server.

The problem is that it is not styled well because in this lib this is not right
```
size.width = elem.offsetWidth;
size.height = elem.offsetHeight;
```
The width which is a calculated width for 33% or 50% or so on, but the height is coming from an inner component which it seems it is not present at the moment when getSize is called.

I think the problem could be, that the components are lazy loaded components and so the height could be dynamic and not right at the moment masonry.layout() do the work.

So not sure if this could be a bug, but is there a solution for a workaround for it?

Thx a lot

**Comment by desandro** [comment]
Thanks for reporting this issue. If you could provide a **reduced test case** of this issue, like in a CodePen, I would be better prepared to address the issue.
