### ISSUE TITLE
getStyle returns null if loaded through an iframe

### ISSUE THREAD

**Issue by brian-mann** [desandro/get-size#5]
Okay so I realize this is a pretty extreme edge case, but this is a problem nevertheless... Let me try to explain.

I'm opening an issue here even though my problem is with Masonry -- I've tracked it back to this dependency.

What's the problem?
You cannot load Masonry directly into an iframe in Firefox (I'm using latest version at this time v31), but yes it works just fine in Chrome.

Okay why does it fail?

During this function https://github.com/desandro/get-size/blob/master/get-size.js#L93 you create a random div and run some tests against this.  The problem is the `getStyle` function will return null. Even though the global `window.getComputedStyle` is available, it will simply return null.  Once style returns null it immediately errors out on the next line, since you cannot call `style.width` on a null value.

I'm not sure how to fix this, I'd have to dig into why loading directly into an iframe causes `getComputedStyle` to return null - but it does.

However, I was able to work around this in my case by simple loading Masonry in the parent window, and then referencing it into the iframe by simply writing `window.Masonry = parent.Masonry` within the iframe.  This ends up achieving the result I'm going for, but it's a hacky work-a-round for not being able to load it naturally into an iframe.

**Comment by desandro** [comment]
[Firefox bug appears to be resolved.](https://bugzilla.mozilla.org/show_bug.cgi?id=548397) I've removed relevant code from getSize v3
