### ISSUE TITLE
Only works in IE11 after a refresh (or with Developer Tools open)

### ISSUE THREAD

**Issue by badeend** [desandro/get-size#6]
The getSize function returns the wrong values in IE11 when the page is just opened (not refreshed).
After a refresh (F5) it does return the right width.

I've narrowed it down to the following problem:

On line 95, the variable isBoxSizeOuter is set:
`isBoxSizeOuter = getStyleSize( style.width ) === 200;`
On IE11 this value seems to randomly 'jump' between true and false.

Inserting the following line, seems to fix it:
`if (!!navigator.userAgent.match(/Trident.*rv[ :]*11\./)) isBoxSizeOuter = false;`

**Comment by desandro** [comment]
getSize v3 does not support IE11. Closing this one as a wontfix.
